inherit_gem:
  rubocop-rails_config:
    - config/rails.yml
require: rubocop-rspec
AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - app/assets/**/*
    - bin/**/*
    - config/**/*
    - db/**/*
    - vendor/**/*
    - tmp/**/*

Layout/IndentHash:
  EnforcedStyle: consistent
Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
Layout/AlignArray:
  Enabled: true
Layout/AlignHash:
  Enabled: true
Layout/EmptyLineAfterGuardClause:
  Enabled: true
Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: space
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  EnforcedStyle: no_space

Lint/UnusedMethodArgument:
  Enabled: true
Lint/UselessAssignment:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
Metrics/LineLength:
  Exclude:
    - 'spec/**/*.rb'
  Max: 100
Metrics/LineLength:
  Include:
    - 'spec/**/*.rb'
  Max: 120
Metrics/MethodLength:
  Enabled: true
Metrics/ClassLength:
  Enabled: true
  Max: 125
Metrics/ParameterLists:
  Enabled: true
Metrics/CyclomaticComplexity:
  Enabled: true
Metrics/AbcSize:
  Enabled: true

Rails/InverseOf:
  Enabled: true

RSpec/MessageSpies:
  EnforcedStyle: receive

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
Style/NumericLiterals:
  Enabled: true
Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/AndOr:
  Enabled: true
Style/ClassCheck:
  Enabled: true
Style/GuardClause:
  Enabled: true

Security/Eval:
  Enabled: true
Security/JSONLoad:
  Enabled: true
Security/JSONLoad:
  Enabled: true
Security/YAMLLoad:
  Enabled: true
