require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-factory_bot
AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - app/assets/**/*
    - bin/**/*
    - config/**/*
    - db/**/*
    - lib/proto/**/*
    - vendor/**/*
    - tmp/**/*

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
Layout/EmptyLinesAroundAccessModifier:
  Enabled: true
Layout/ArrayAlignment:
  Enabled: true
Layout/HashAlignment:
  Enabled: true
Layout/EmptyLineAfterGuardClause:
  Enabled: true
Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space
Layout/LineLength:
  Max: 100
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true
Lint/UselessAssignment:
  Enabled: true

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - lib/tasks/*
    - lib/capistrano/tasks/*
    - Guardfile
Metrics/MethodLength:
  Enabled: true
  Max: 15
Metrics/ClassLength:
  Enabled: true
  Max: 200
Metrics/ModuleLength:
  Max: 200
Metrics/ParameterLists:
  Enabled: true
Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 15
Metrics/PerceivedComplexity:
  Max: 15
Metrics/AbcSize:
  Enabled: true
  Max: 20

Naming/MemoizedInstanceVariableName:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Naming/VariableNumber:
  Enabled: false

Rails/SquishedSQLHeredocs:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/RenderInline:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
Style/FetchEnvVar:
  Enabled: false
Style/NumericLiterals:
  Enabled: true
Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/AndOr:
  Enabled: true
Style/ClassCheck:
  Enabled: true
Style/GuardClause:
  Enabled: true
Style/HashSyntax:
  Enabled: false
Style/CommentAnnotation:
  Enabled: false

Security/Eval:
  Enabled: true
Security/JSONLoad:
  Enabled: true
Security/YAMLLoad:
  Enabled: true

# Temporary Cops
Rails/HelperInstanceVariable:
  Enabled: false
Rails/LexicallyScopedActionFilter:
  Enabled: false
Rails/UniqueValidationWithoutIndex:
  Enabled: false
Rails/Output:
  Enabled: false

# Investigate
Rails/ActionControllerFlashBeforeRender:
  Enabled: false
