# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_update.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("user_update.proto", :syntax => :proto3) do
    add_message "b_p_s.update.UserDataImport" do
      repeated :created, :message, 1, "b_p_s.update.User"
      repeated :updated, :message, 2, "b_p_s.update.UserUpdate"
      repeated :completions, :message, 3, "b_p_s.update.UserCompletion"
      repeated :families, :message, 4, "b_p_s.update.UserFamily"
      optional :locked, :bool, 5
      repeated :not_in_import, :message, 6, "b_p_s.update.User"
    end
    add_message "b_p_s.update.User" do
      optional :id, :int64, 1
      optional :certificate, :string, 2
      optional :name, :string, 3
    end
    add_message "b_p_s.update.UserUpdate" do
      optional :user, :message, 1, "b_p_s.update.User"
      repeated :changes, :message, 2, "b_p_s.update.UserChange"
    end
    add_message "b_p_s.update.UserChange" do
      optional :field, :string, 1
      optional :from, :string, 2
      optional :to, :string, 3
    end
    add_message "b_p_s.update.UserCompletion" do
      optional :user, :message, 1, "b_p_s.update.User"
      repeated :completions, :message, 2, "b_p_s.update.Completion"
    end
    add_message "b_p_s.update.Completion" do
      optional :key, :string, 1
      optional :date, :message, 2, "google.protobuf.Timestamp"
    end
    add_message "b_p_s.update.UserFamily" do
      optional :user, :message, 1, "b_p_s.update.User"
      repeated :family, :message, 2, "b_p_s.update.User"
    end
  end
end

module BPS
  module Update
    UserDataImport = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("b_p_s.update.UserDataImport").msgclass
    User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("b_p_s.update.User").msgclass
    UserUpdate = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("b_p_s.update.UserUpdate").msgclass
    UserChange = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("b_p_s.update.UserChange").msgclass
    UserCompletion = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("b_p_s.update.UserCompletion").msgclass
    Completion = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("b_p_s.update.Completion").msgclass
    UserFamily = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("b_p_s.update.UserFamily").msgclass
  end
end
