AllCops:
  NewCops: enable

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
Layout/HashAlignment:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19
  EnforcedShorthandSyntax: either
