bridge_office:
  commander:
    - admin
  executive:
    - admin
  educational:
    - education
  administrative:
    - users
    - calendar
    - event
  secretary:
    - admin
  treasurer:
    - property
    - store
  asst_educational:
    - education
  asst_secretary:
    - newsletter
    - calendar
    - photos
    - minutes
    - page
committee:
  Seminars:
    - seminar
  Vessel Safety Check:
    - vsc
  Ship's Store:
    - store
  Webmaster:
    - page
    - calendar
    - photos
  Newsletter Editor:
    - newsletter
  Meetings & Programs:
    - event
  Rendezvous:
    - event
  Change of Watch:
    - event
  Membership:
    - users
  Roster / Database:
    - roster
  On-the-Water Training:
    - otw
