# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0db43d732ae87f72dd72c676956535d83666cda793fffef09fbf1ce525506a15699c25f953c72414be9df34061526b90995c2dd563fca8a65dc4a5288c7647ca
  s3_access_key: <%= ENV["S3_ACCESS_KEY"] %>
  s3_secret: <%= ENV["S3_SECRET"] %>
  cf_keypair_id: <%= ENV['CLOUDFRONT_KEYPAIR_ID'] %>
  cf_private_key_path: <%= "#{Rails.root}/config/keys/pk-#{ENV['CLOUDFRONT_KEYPAIR_ID']}.pem" %>

test:
  secret_key_base: 7239f6eb45fe5fa7a5e3d7cd41da5aa3ed54f2636bcc90c787a1534132674821616433278d9c139c93da087060a07e68c934ecf4d0ae6c33e0e9d338ed87f373
  s3_access_key: <%= ENV["S3_ACCESS_KEY"] %>
  s3_secret: <%= ENV["S3_SECRET"] %>
  cf_keypair_id: <%= ENV['CLOUDFRONT_KEYPAIR_ID'] %>
  cf_private_key_path: <%= "#{Rails.root}/config/keys/pk-#{ENV['CLOUDFRONT_KEYPAIR_ID']}.pem" %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  s3_access_key: <%= ENV["S3_ACCESS_KEY"] %>
  s3_secret: <%= ENV["S3_SECRET"] %>
  cf_keypair_id: <%= ENV['CLOUDFRONT_KEYPAIR_ID'] %>
  cf_private_key_path: <%= "#{Rails.root}/config/keys/pk-#{ENV['CLOUDFRONT_KEYPAIR_ID']}.pem" %>
