AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: true
  Exclude:
    - aws_stub_responses.rb

Naming/MethodParameterName:
  Enabled: false
Naming/VariableNumber:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
RSpec/ExpectChange:
  Enabled: false
RSpec/LetSetup:
  Enabled: false
RSpec/MessageSpies:
  EnforcedStyle: receive
RSpec/InstanceVariable:
  Enabled: false
  # AssignmentOnly: true
RSpec/NestedGroups:
  Max: 10
RSpec/EmptyExampleGroup:
  Enabled: true
  Exclude:
    - models/event_spec.rb
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/IndexedLet:
  Enabled: false

Rails/SquishedSQLHeredocs:
    Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/HashSyntax:
  Enabled: false

# Temporary cops
RSpec/MultipleExpectations:
  Max: 10
Style/MixinUsage:
  Enabled: false
