Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: true
  Exclude:
    - aws_stub_responses.rb
Style/GlobalVars:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
RSpec/MessageSpies:
  EnforcedStyle: receive
RSpec/InstanceVariable:
  Enabled: false
  # AssignmentOnly: true
RSpec/NestedGroups:
  Max: 10

RSpec/EmptyExampleGroup:
  Enabled: true
  Exclude:
    - models/event_spec.rb

# Temporary cops
RSpec/MultipleExpectations:
  Max: 10
Style/MixinUsage:
  Enabled: false
